[project]
name = "pydantic-in-10-min"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "devtools>=0.12.2",
    "pydantic>=2.10.5",
    "ruff>=0.9.5",
]
